### ISSUE TITLE
Change repository settings

### ISSUE THREAD

**Issue by AlekSi** [cristalhq/bson#38]
I think it makes sense to enable branch protection rules (or newer rulesets) to require CI to pass.

**Comment by cristaloleg** [comment]
IMO looks good.

<img width="762" alt="image" src="https://github.com/cristalhq/bson/assets/366002/54edb59f-89ea-4d33-8d4c-9b236aa240b7">

**Comment by AlekSi** [comment]
I think "Require branches to be up to date before merging" should be enabled, too. More importantly, right under it specific CI jobs should be required.

Right now, we have this:
![CleanShot 2023-12-18 at 12 06 33@2x](https://github.com/cristalhq/bson/assets/11512/a54dcee3-c619-47ea-9b40-b46031b00e68)

What we should have is this:
![CleanShot 2023-12-18 at 12 07 00@2x](https://github.com/cristalhq/bson/assets/11512/6a9422da-c347-4afe-a07a-4ee11fae7629)

**Comment by cristaloleg** [comment]
Got it. Well, I don't have a strong preferences here but let's require them. IMO `vuln` shouldn't be required.

<img width="771" alt="image" src="https://github.com/cristalhq/bson/assets/366002/1d6656a4-4111-4ab5-8d87-a7d599b26624">

**Comment by cristaloleg** [comment]
Proof: 
<img width="871" alt="image" src="https://github.com/cristalhq/bson/assets/366002/b439e1ce-99ba-4a86-953d-b332f75ee457">

**Comment by cristaloleg** [comment]
Fixed
