### ISSUE TITLE
Add logging helpers to `bsonproto`

### ISSUE THREAD

**Issue by AlekSi** [cristalhq/bson#41]
```go
func LogValue[T ScalarType](v T) slog.Value
func LogValueAny(v any) slog.Value
```

or

```go
func GoString[T ScalarType](v T) string
func GoString(v any) string
```

given that the representation is always a Go-code-like string? For example, `int32(42)` and `int64(42)`.

**Comment by cristaloleg** [comment]
1st option will require bumping Go version in `go.mod`. 2nd looks much simpler :¯\_(ツ)_/¯

**Comment by AlekSi** [comment]
After [implementing it](https://github.com/FerretDB/FerretDB/blob/main/internal/bson/logging.go) multiple times in multiple forms, I no longer think there is a good universal output format for BSON values. In some cases, you would want to preserve type information (for example, to output int32, int64, and float64 differently); sometimes, you don't (for example, to output all numbers as just numbers to make them indexable in the logs storage). It is use-case-specific and even handler-specific (text handler essentially removes all type information).

I think we could close that one.
